Comment out failure step for vulnerability detection in Trivy workflows

diff --git a/.github/workflows/trivy-sast.yml b/.github/workflows/trivy-sast.yml
--- a/.github/workflows/trivy-sast.yml
+++ b/.github/workflows/trivy-sast.yml
@@ -169,8 +169,8 @@ jobs:
           trivy_report: ${{ inputs['output-format'] == 'table' && env.TRIVY_RESULTS_FILE || env.TRIVY_PR_REPORT_FILE }}
           fail_on_severity: ${{ inputs['fail-on-severity'] }}
 
-      - name: Falhar se vulnerabilidades encontradas
-        if: ${{ inputs['exit-on-vulnerability'] && (steps.trivy-sast-template.outcome == 'failure' || steps.trivy-sast.outcome == 'failure') }}
-        run: |
-          echo "Trivy encontrou vulnerabilidades com severidade configurada."
-          exit 1
+      # - name: Falhar se vulnerabilidades encontradas
+      #   if: ${{ inputs['exit-on-vulnerability'] && (steps.trivy-sast-template.outcome == 'failure' || steps.trivy-sast.outcome == 'failure') }}
+      #   run: |
+      #     echo "Trivy encontrou vulnerabilidades com severidade configurada."
+      #     exit 1
diff --git a/.github/workflows/trivy-sca.yml b/.github/workflows/trivy-sca.yml
--- a/.github/workflows/trivy-sca.yml
+++ b/.github/workflows/trivy-sca.yml
@@ -204,8 +204,8 @@ jobs:
           trivy_report: ${{ env.TRIVY_TABLE_FILE }}
           fail_on_severity: ${{ inputs['fail-on-severity'] }}
 
-      - name: Falhar se vulnerabilidades encontradas
-        if: ${{ inputs['exit-on-vulnerability'] && (steps.trivy-sca-template.outcome == 'failure' || steps.trivy-sca.outcome == 'failure') }}
-        run: |
-          echo "Trivy encontrou vulnerabilidades com severidade configurada."
-          exit 1
+      # - name: Falhar se vulnerabilidades encontradas
+      #   if: ${{ inputs['exit-on-vulnerability'] && (steps.trivy-sca-template.outcome == 'failure' || steps.trivy-sca.outcome == 'failure') }}
+      #   run: |
+      #     echo "Trivy encontrou vulnerabilidades com severidade configurada."
+      #     exit 1
